import core from "./core.json";
import pace from "./pace.json";
import paceExtended from "./pace-extended.json";
import clientCare from "./client-care.json";
import clientCareExtended from "./client-care-extended.json";
import vulnerability from "./vulnerability.json";
import vulnerabilityExtended from "./vulnerability-extended.json";
import disclosure from "./disclosure.json";
import disclosureExtended from "./disclosure-extended.json";
import interview from "./interview.json";
import interviewExtended from "./interview-extended.json";
import evidence from "./evidence.json";
import evidenceExtended from "./evidence-extended.json";
import bail from "./bail.json";
import bailExtended from "./bail-extended.json";
import portfolio from "./portfolio.json";
import portfolioExtended from "./portfolio-extended.json";
import authorityToAct from "./authority-to-act.json";
import telephoneAdvice from "./telephone-advice.json";
import identification from "./identification.json";
import interviewRecording from "./interview-recording.json";
import charging from "./charging.json";
import citScenarios from "./cit-scenarios.json";
import registerEntry from "./register-entry.json";
import probationaryExtended from "./probationary-extended.json";
import delayLegalAdvice from "./delay-legal-advice.json";
import voluntaryAttendance from "./voluntary-attendance.json";
import nfaCautions from "./nfa-cautions.json";
import varietySamples from "./variety-samples.json";

export const questions = [
  ...(core.questions ?? []),
  ...(pace.questions ?? []),
  ...(paceExtended.questions ?? []),
  ...(clientCare.questions ?? []),
  ...(clientCareExtended.questions ?? []),
  ...(vulnerability.questions ?? []),
  ...(vulnerabilityExtended.questions ?? []),
  ...(disclosure.questions ?? []),
  ...(disclosureExtended.questions ?? []),
  ...(interview.questions ?? []),
  ...(interviewExtended.questions ?? []),
  ...(evidence.questions ?? []),
  ...(evidenceExtended.questions ?? []),
  ...(bail.questions ?? []),
  ...(bailExtended.questions ?? []),
  ...(portfolio.questions ?? []),
  ...(portfolioExtended.questions ?? []),
  ...(authorityToAct.questions ?? []),
  ...(telephoneAdvice.questions ?? []),
  ...(identification.questions ?? []),
  ...(interviewRecording.questions ?? []),
  ...(charging.questions ?? []),
  ...(citScenarios.questions ?? []),
  ...(registerEntry.questions ?? []),
  ...(probationaryExtended.questions ?? []),
  ...(delayLegalAdvice.questions ?? []),
  ...(voluntaryAttendance.questions ?? []),
  ...(nfaCautions.questions ?? []),
  ...(varietySamples.questions ?? []),
];

/**
 * User-facing training question set.
 *
 * We keep autogenerated “coverage seeding” questions in `questions` for tooling,
 * but exclude them from training flows (Practice / Mock Exam) to avoid low-signal items.
 */
export const trainingQuestions = questions.filter(
  (q: any) => typeof q?.id === "string" && !q.id.startsWith("gen-")
);

const questionsModule = { questions, trainingQuestions };
export default questionsModule;

